const number1 = 5;
const number2 = 2;
const product = number1 * number2;
console.log('value of product:', product);
console.log('typeof product:', typeof product);
const charge = 16;
const payment = 8;
const amountRemaining = charge - payment;
console.log('value of amountRemaining:', amountRemaining);
console.log('typeof amountRemaining:', typeof amountRemaining);
const tests = 13;
const assignments = 30;
const final = 10;
const grade = (tests + assignments + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Karina';
const lastName = 'Kim';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 5;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('type of isAcidic:', typeof isAcidic);
const numberOfSoldiers = 321;
const isSparta = numberOfSoldiers === 300;
console.log('value of isSparta:', isSparta);
console.log('type of isSparta:', typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT';
console.log('value of nickname:', nickname);
console.log('type of nickname:', typeof nickname);
